#!/bin/bash
# set -x
set -e

SCRIPT_PATH="$(dirname -- "${BASH_SOURCE[0]}")"
TMP_PATH="/tmp/jsc-build"
LOG_PATH="${TMP_PATH}/build_log.txt"

rm -rf ${TMP_PATH}
mkdir -p ${TMP_PATH}
touch ${LOG_PATH}

echo -e "> Generating AST json"
${SCRIPT_PATH}/jscompiler/generate_json_ast $1 ${TMP_PATH}/ast.json &> ${LOG_PATH}

echo -e "> Generating AST c++ constexpr representation"
command -v json2cpp &> /dev/null || { echo >&2 "json2cpp is required. Aborting."; exit 1; }
${SCRIPT_PATH}/jscompiler/json2cpp prog ${TMP_PATH}/ast.json ${TMP_PATH}/ast &> ${LOG_PATH}

echo -e "> Compiling AST to exe"
command -v cmake &> /dev/null || { echo >&2 "cmake is required. Aborting."; exit 1; }
echo -e "  > Configuring with cmake"
cmake ${SCRIPT_PATH}/../etc/jscompiler -B ${TMP_PATH} -DCMAKE_BUILD_TYPE=RelWithDebInfo &> ${LOG_PATH} || { echo >&2 "cmake configure step failed. Aborting."; exit 1; }
echo -e "  > Building with cmake"
cmake --build ${TMP_PATH} &> ${LOG_PATH} || { echo >&2 "cmake build step failed. Aborting."; exit 1; }
